### PR TITLE
azuredisk-csi-driver: bump to v1.1.1

### PR DESCRIPTION
**Pull request by dkoshkin**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

Bump version to latest https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/charts/v1.1.1
Updating specs to better match latest version so its easier to upgrade in the future.

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/COPS-6851?src=confmacro

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by dkoshkin** [comment]
Also tested to make sure upgrades from a previous version still all work.

**Review by hectorj2f — APPROVED** [review]

**Comment by dkoshkin** [comment]
This is a good to have but doesn't actually fix the COPS ticket, see [upstream issue](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/767)

**Review by sebbrandt87 — APPROVED** [review]
lgtm

**Review by alejandroEsc — APPROVED** [review]
a lot of changes, but lgtm

**Pull request merged**
