### PR TITLE
[velero] bump to version 1.5.2 and minio 8.0.8

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What type of PR is this?**

cchore

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-72964

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by s12chung** [comment]
i wonder if we can use minio as a subchart 🤔

**Comment by alejandroEsc** [comment]
> i wonder if we can use minio as a subchart 🤔

not sure i understand, it is a subchart here

**Comment by s12chung** [comment]
ah,  i mean as a `.tar.gz` like elsewhere, so we don't need to track the diff.

**Comment by alejandroEsc** [comment]
> ah, i mean as a `.tar.gz` like elsewhere, so we don't need to track the diff.

that is a great idea. ill look into it once i feel things are working

**Comment by s12chung** [comment]
> ah, i mean as a .tar.gz like elsewhere, so we don't need to track the diff.

can't do anymore,  as I customized the chart. see: https://github.com/mesosphere/charts/pull/937/commits/f3154667a5178890893757b442890aa530dec51c

tested with this addon: https://github.com/mesosphere/kubernetes-base-addons/pull/790

the `kubeaddons-extrasteps` changes are here: https://github.com/mesosphere/kubeaddons-extrasteps/pull/188., which is used in the helm values below:

```yaml
enableHelmHooks: false # handle helm install --atomic through kubeaddons
configuration:
  provider: "aws"
  backupStorageLocation:
    bucket: "velero"
    config:
      region: "fallback"     # enables non-production fallback minio backend
      s3Url: http://minio.velero.svc:9000
      s3ForcePathStyle: true
      insecureSkipTLSVerify: "true"
  volumeSnapshotLocation:
    config:
      region: "fallback"
credentials:
  name: velero-kubeaddons
  secretContents:
    cloud: "placeholder"
schedules:
  default:
    schedule: "0 0 * * *"
    template:
      ttl: 720h # 30 day retention, required to create schedule
metrics:
  enabled: true
  service:
    labels:
      servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
initContainers:
  - name: initialize-velero
    image: s12chung/kubeaddons-addon-initializer:latest
    args: ["velero"]
    env:
      - name: "VELERO_MINIO_FALLBACK_SECRET_NAME"
        value: "velero-kubeaddons"
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.1.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
minioBackend: true
minio:
  mode: distributed
  defaultBucket:
    enabled: true
    name: velero
  bucketRoot: "/data"
  mountPath: "/data"
  existingSecret: minio-creds-secret
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 750m
  persistence:
    size: 10Gi
  ingress:
    enabled: true
    hosts:
      - ""
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/frontend-entry-points: velero-minio
```

**Comment by s12chung** [comment]
tested with this addon: https://github.com/mesosphere/kubernetes-base-addons/pull/790

the `kubeaddons-extrasteps` changes are here: https://github.com/mesosphere/kubeaddons-extrasteps/pull/188., which is used in the helm values below:

```yaml
enableHelmHooks: false # handle helm install --atomic through kubeaddons
configuration:
  provider: "aws"
  backupStorageLocation:
    bucket: "velero"
    config:
      region: "fallback"     # enables non-production fallback minio backend
      s3Url: http://minio.velero.svc:9000
      s3ForcePathStyle: true
      insecureSkipTLSVerify: "true"
  volumeSnapshotLocation:
    config:
      region: "fallback"
credentials:
  name: velero-kubeaddons
  secretContents:
    cloud: "placeholder"
schedules:
  default:
    schedule: "0 0 * * *"
    template:
      ttl: 720h # 30 day retention, required to create schedule
metrics:
  enabled: true
  service:
    labels:
      servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
initContainers:
  - name: initialize-velero
    image: s12chung/kubeaddons-addon-initializer:latest
    args: ["velero"]
    env:
      - name: "VELERO_MINIO_FALLBACK_SECRET_NAME"
        value: "velero-kubeaddons"
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.1.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
minioBackend: true
minio:
  mode: distributed
  defaultBucket:
    enabled: true
    name: velero
  bucketRoot: "/data"
  mountPath: "/data"
  existingSecret: minio-creds-secret
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 750m
  persistence:
    size: 10Gi
  ingress:
    enabled: true
    hosts:
      - ""
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/frontend-entry-points: velero-minio
```

**Review by s12chung — APPROVED** [review]

**Review by gracedo — APPROVED** [review]
Will admit there are a lot of changes I don't quite understand but as most of it is pulled from upstream and it looks like this has all been tested fairly thoroughly, so :shipit:

**Pull request merged**
