### PR TITLE
[kubefed] update charts and enable better helm3 migration

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

This allows for our tooling to allow kubefed to deploy from a helm2 or a helm3 driver just fine. 

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-70708

**Special notes for your reviewer**:
Tested this using helm2 and helm3 for installation and uninstallation, now issues helm3 is much faster. 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by alejandroEsc** [comment]
> @alejandroEsc Do we need to do this now considering we have a community helmv3 chart coming soon? My preferred option is to align our chart and upstream (rather drop our chart and use upstream directly).

Please, no need to block this PR in either case this merge does not counter any of your points.

To answer your question, the upstream chart will only work with helm3 and we are not fully committing to helm3 as we will have customers who may for some time still use helm2. The hard transition upstream will make this very difficult on us. In addition they do not today manage the crds as we do today. For these reasons we  should maintain this code a bit longer. Now with that said I can totally work with the upstream chart and contribute to it with the changes here (which includes the cert-manager changese) as it is one of my goals to do so.

**Comment by makkes** [comment]
> > @alejandroEsc Do we need to do this now considering we have a community helmv3 chart coming soon? My preferred option is to align our chart and upstream (rather drop our chart and use upstream directly).
> 
> Please, no need to block this PR in either case this merge does not counter any of your points.
> 
> To answer your question, the upstream chart will only work with helm3 and we are not fully committing to helm3 as we will have customers who may for some time still use helm2. The hard transition upstream will make this very difficult on us. In addition they do not today manage the crds as we do today. For these reasons we should maintain this code a bit longer. Now with that said I can totally work with the upstream chart and contribute to it with the changes here (which includes the cert-manager changese) as it is one of my goals to do so.

@alejandroEsc maybe we can drive the [upstream chart PR](https://github.com/kubernetes-sigs/kubefed/pull/1260) into the direction of making the chart compatible with v2 **and** v3?

**Comment by jimmidyson** [comment]
@alejandroEsc I blocked it because I guess I'm confused and disappointed why we haven't driven these changes upstream as I requested in Slack discussion with you (https://mesosphere.slack.com/archives/CSR6U1YD6/p1596041773057600 , https://mesosphere.slack.com/archives/CSR6U1YD6/p1596056145059700). This was a surprise when I've seen you approve the upsteam helm3 PR. I really don't want to maintain our own chart any longer than we have to and this looked like a good opportunity to align. As kubefed maintainers, we have enough control of the project to guide it to fit our own needs, but it looks as though the charts are not yet converging.

> I can totally work with the upstream chart and contribute to it with the changes here (which includes the cert-manager changese) as it is one of my goals to do so.

That is great to hear - I'm excited to see that happen ASAP! Having our forked chart is bad for us (extra maintenance) and bad for the community (if we need stuff in our charts then it should be pushed upstream to benefit the community). Can you link (or create as necessary) JIRAs for that work to align the charts and give me some idea of the priority of that work please?

**Comment by makkes** [comment]
Maybe a little clarification about the `staging` directory also helps: We have imposed the policy onto ourselves to only make changes to any chart in there with an accompanying upstream PR:

> A chart PR into the staging repository will not be accepted without an accompanying upstream pull request.

[source](https://github.com/mesosphere/charts#repository-structure)

Following that policy, the only way forward here is to change the [upstream PR](https://github.com/kubernetes-sigs/kubefed/pull/1260) that's already in place or move our own version of the kubefed chart into the `stable` directory (which I assume is something we want to avoid).

**Comment by alejandroEsc** [comment]
> @alejandroEsc I blocked it because I guess I'm confused and disappointed why we haven't driven these changes upstream as I requested in Slack discussion with you (https://mesosphere.slack.com/archives/CSR6U1YD6/p1596041773057600 , https://mesosphere.slack.com/archives/CSR6U1YD6/p1596056145059700). This was a surprise when I've seen you approve the upsteam helm3 PR. I really don't want to maintain our own chart any longer than we have to and this looked like a good opportunity to align. As kubefed maintainers, we have enough control of the project to guide it to fit our own needs, but it looks as though the charts are not yet converging.
> 
> > I can totally work with the upstream chart and contribute to it with the changes here (which includes the cert-manager changese) as it is one of my goals to do so.
> 
> That is great to hear - I'm excited to see that happen ASAP! Having our forked chart is bad for us (extra maintenance) and bad for the community (if we need stuff in our charts then it should be pushed upstream to benefit the community). Can you link (or create as necessary) JIRAs for that work to align the charts and give me some idea of the priority of that work please?

Actually to your first point yeah these are not diverging, BUT, until we make the full move to helm3 i do no see how we could support the helm3 chart upstream. I did ask several times if we are making a hard to helm3 and i got an affirmative several times. Regardless there are things that I will be contributinig back and I cannot do so when I have other more pressing priorities or Chart changes that are more important in the kubefed repo which would entail me having to do a lot of rebases. I will do so soon, make the necessary changes, but as for maintaining helm2 and helm3 charts this is necessary and i do not see a way around it.

**Comment by alejandroEsc** [comment]
> Maybe a little clarification about the `staging` directory also helps: We have imposed the policy onto ourselves to only make changes to any chart in there with an accompanying upstream PR:
> 
> > A chart PR into the staging repository will not be accepted without an accompanying upstream pull request.
> 
> [source](https://github.com/mesosphere/charts#repository-structure)
> 
> Following that policy, the only way forward here is to change the [upstream PR](https://github.com/kubernetes-sigs/kubefed/pull/1260) that's already in place or move our own version of the kubefed chart into the `stable` directory (which I assume is something we want to avoid).

There are a few charts here that do not follow this guideline. I am willing to remove if it is a source of contention.

**Comment by makkes** [comment]
> > Maybe a little clarification about the `staging` directory also helps: We have imposed the policy onto ourselves to only make changes to any chart in there with an accompanying upstream PR:
> > > A chart PR into the staging repository will not be accepted without an accompanying upstream pull request.
> > 
> > 
> > [source](https://github.com/mesosphere/charts#repository-structure)
> > Following that policy, the only way forward here is to change the [upstream PR](https://github.com/kubernetes-sigs/kubefed/pull/1260) that's already in place or move our own version of the kubefed chart into the `stable` directory (which I assume is something we want to avoid).
> 
> There are a few charts here that do not follow this guideline.

Yeah, that's [broken windows theory](https://en.wikipedia.org/wiki/Broken_windows_theory) in effect. 😆 We can get out of this, though, leading by example.

**Comment by alejandroEsc** [comment]
Closing this PR as we will try to migrate away from this chart.

**Comment by jimmidyson** [comment]
I'm confused - you [said](https://github.com/mesosphere/charts/pull/725#issuecomment-672545689):

> Closing this PR as we will try to migrate away from this chart.

but then you've pushed changes after that. What is the status of this PR?

**Comment by alejandroEsc** [comment]
> I'm confused - you [said](https://github.com/mesosphere/charts/pull/725#issuecomment-672545689):
> 
> > Closing this PR as we will try to migrate away from this chart.
> 
> but then you've pushed changes after that. What is the status of this PR?

using this to test chart testing... thats all im closing this out soon.

**Comment by alejandroEsc** [comment]
closing.

**Pull request closed without merging**
