### PR TITLE
kubecost: Upgrade chart to 1.69.0

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

Upgrade base kubecost to 1.69.0
https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.69.0
```
App

AWS Out of cluster assets now visible from Assets
Better AWS status messages on invalid credentials on Settings
Faster AWS pricing data download on regional clusters!
More accurate network costs pulled from AWS Cost and Usage Report
Better support for k8s 1.17+ labels
[Fix] Assorted panic fixes on Prometheus errors
Added ability to generate a cost-by-node view on Reports.
Note that shared idle allocation still distributes cluster cost relative to the containers running on the node, not the actual node price in the infrastructure. To see the full node price, use the view on assets.html
Fix inaccuracy on Thanos query downsampling
Add new diagnostics view
Network Costs Daemonset

Track network ingress metrics in Prometheus
Helm Chart

Support supplying enterprise license key via secret
```
https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.68.1
```
Fix panic related to unexpected prometheus errors
Fix an asynchronous issue where reconciliation data from AWS would occasionally not be built on pod startup
Fix a UI issue where the frontend sometimes displayed that enterprise features were not turned on
Extend Thanos compact raw metric retention and support querying over windows where downsampling data is available.
```
https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.68.0
```
App:

Fix log concurrency issue
Fix panic on nil cache read
Memory optimizations
Support partial rebuilds of ETL cache
Filter assets by prefixes
Support custom date ranges on assets.html
Add prometheus health dashboards to grafana
Add ability to get clustername from external label clusterid
```

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubecost: Add prometheus health dashboards to grafana
```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by alejandroEsc — APPROVED** [review]
No blocking, maybe have to use `helm2 dep update?`

**Review by samvantran — APPROVED** [review]
❤️ those release notes.

Should this be a 0.3.0? One of the upstream notes reported now being able to supply license key via secret

**Comment by gracedo** [comment]
@samvantran tbh not entirely sure how we have been versioning our charts here, we don't _seem_ to be following semantic versioning for the most part. the last minor bump I did in this chart was when kubecost upgraded thanos to 0.15 which was a significant upgrade, but I don't see any changes as significant as that one in this set of changes. going by semver, yes this would be a minor bump due to new feats :) I'm fine either way but it does seem better to follow an established process over an undefined one so I'll bump this to 0.3.0 (and maybe we should decide on versioning strategy across our charts?)

**Comment by samvantran** [comment]
@gracedo you own this chart. you get to decide 😄 

if you want to establish a process, talk to @joejulian + catalog. would be great to see a consistent versioning plan

**Pull request merged**
