### PR TITLE
chore: update kubefed to 0.4.1

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by gracedo — APPROVED** [review]

**Review by joejulian — APPROVED** [review]

**Comment by makkes** [comment]
It looks like the Istion Addon is flapping between `deploying` and `absent`:
```    experimental_logging_hooks.go:88: cluster addon istio has reached stage deploying
[11:49:16]
    experimental_logging_hooks.go:88: cluster addon istio has reached stage absent
```

https://teamcity.mesosphere.io/viewLog.html?buildTypeId=kubeaddons_KubernetesBaseAddons&buildId=2956153&tab=buildLog&logTab=tree&filter=debug&expand=all&_focus=926

**Comment by makkes** [comment]
I wonder, though, whether we even need the `test-helm2` check as we're dropping support for Helm v2, anyway, don't we?

**Comment by makkes** [comment]
I'm not sure how my comments ended up here. I figure they were meant for https://github.com/mesosphere/kubernetes-base-addons/pull/571.

**Comment by samvantran** [comment]
> I wonder, though, whether we even need the test-helm2 check as we're dropping support for Helm v2, anyway, don't we?

Yeah maybe we can remove the helm2 CI check (or at least make non-required) but keep the build config and manually trigger tests whenever we make fixes to previous versions of charts/KBA

**Pull request closed without merging**
