### PR TITLE
prometheus-operator: Improve grafana dashboard names/tags, cleanup

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

- Add `Addon / ` prefix to our addon dashboards
- Clean up the tags on those dashboards
- Remove local volume usage dashboard as it is included in the `Kubernetes / Persistent Volume` dashboard included with the chart
- Remove unused dashboards from values file

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-69721

**Special notes for your reviewer**:
Previously:
image
image

With updates:
image
image

The remaining un-namespaced/un-tagged dashboards are ones I don't have control over as they are controlled and autogenerated by upstream. You can also test this by using this kba branch: `gracedo/prom_improve_dash_names_D2IQ-70057`

**Does this PR introduce a user-facing change?**:

```release-note
Improve Grafana dashboard names and tags for dashboards tied to addons
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by jieyu** [comment]
Thank you for doing this!

a couple of nits:
1) what's the difference between `Prometheus` and `Addons / Prometheus 2.0 Overview`?
2) can we add `addons` tag for all the addon dashboards?
3) I'll move Calico, CoreDNS, etcd and Autoscaler under `Core Components / xxx`, and add tag `core-components`.

**Comment by gracedo** [comment]
@jieyu 
1. `Prometheus` is a dashboard included in upstream chart. I can remove our `Prometheus 2.0 Overview` dashboard, it's a different dashboard with different graphs but probably confusing now that the upstream chart added its own Prometheus dash.
2. yes!
3. makes sense, will do thanks!

**Comment by hectorj2f** [comment]
What about the Prometheus UI tag ? Is it possible to change it too ?
Screen Shot 2020-07-13 at 4 57 13 PM

**Comment by gracedo** [comment]
> What about the Prometheus UI tag ? Is it possible to change it too ?
> Screen Shot 2020-07-14 at 1 43 59 PM

@hector Unfortunately that dashboard is from upstream :/

**Pull request merged**
