### PR TITLE
Change landing page from /ops/portal to /ops/portal/kommander/ui/

### PR DESCRIPTION
**Pull request by takirala**
**What type of PR is this?**

Feature

**What this PR does/ why we need it**:

Changes the "Launch Console" button in landing page to point to kommander UI instead of opsportal 

**Which issue(s) this PR fixes**:
[D2IQ-74076](https://jira.d2iq.com/browse/D2IQ-74076)

**Special notes for your reviewer**:

Following changes are made in the single line diff:

- Changed `Welcome to Konvoy!` to `Log In to Kommander`
- Changed `/ops/portal` to `/ops/portal/kommander/ui/`. **Will be changed to `/dkp/kommander` before ready**
- Removed `Generate Kubectl Token`
- Added a new css class `.credentials-link{margin-top:16px;display:block}`
- Changed css class for `Credentials Plugin Instructions` from `button` to `credentials-link` 

**Does this PR introduce a user-facing change?**:
TODO

```release-note

```

**Checklist**

TODO

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by TattdCodeMonkey** [comment]
we don't need to do this. This page will not exist for kommander 2.0 and we don't want to adjust it for 1.x

**Comment by takirala** [comment]
@TattdCodeMonkey I thought so too but then when i saw:

> Existing routes redirect to kommander (konvoy, landing page, old kommander etc)
 at https://jira.d2iq.com/browse/D2IQ-74062

i thought this should be updated too. Maybe this is just for documentation update ?!

Made the required changes at https://github.com/mesosphere/dex/pull/9

**Comment by TattdCodeMonkey** [comment]
@takirala we have a ticket for the redirects: https://jira.d2iq.com/browse/D2IQ-74135 basically in Kommander 2.0 we need to make sure all the existing urls redirect to the new kommander url. so going to `/ops/landing` should redirect to `/dkp/kommander` etc. we will also need to update the kommander UI path to `/dkp/kommander` as a part of that ticket.

**Comment by takirala** [comment]
cool, that makes sense - thanks for clarifying rodney!

**Pull request closed without merging**
