### PR TITLE
Update Kommander UI

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
**What type of PR is this?**

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by gracedo — APPROVED** [review]
is this needed for 1.3.0?

**Comment by DanielMSchmidt** [comment]
@gracedo Yeah it's fixing CVE stuff but there is also another one from @natmegs coming with other important stuff

**Comment by natmegs** [comment]
Actually it looks like the one I needed to get in is included in this version too! There may be one more CVE related update coming but it's looking like it will be solved in docs. Will know for sure this afternoon

**Comment by gracedo** [comment]
great thanks! I will make sure to include this bump when I cut the next kommander rc today

**Review by natmegs — APPROVED** [review]

**Comment by gracedo** [comment]
@DanielMSchmidt @natmegs just realized an opsportal bump wasn't included in this pr, can you open a pr to bump ui in opsportal please?

**Pull request merged**
