### PR TITLE
kommander: Fix cost analyzer ingress path

### PR DESCRIPTION
**Pull request by branden**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

This simplifies the ingress by removing path rewrites that are no longer
necessary due to a fix in the cost analyzer. It also fixes a possible
authz error that may be encountered if a user with a role that includes
any restrictions on authorized URLs tries to browse to the cost
analyzer UI.

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-71985

**Special notes for your reviewer**:

I tested this by browsing to `/ops/portal/kommander/kubecost/frontend` (no trailing slash) and observing that I was redirected to `/ops/portal/kommander/kubecost/frontend/` (with trailing slash) and that the UI loaded with no errors. Here's a screenshot from Chrome's dev tools to demonstrate:

Screen Shot 2020-11-10 at 5 48 06 PM

**Does this PR introduce a user-facing change?**:

```release-note
[kommander] Fixes an authz error that may be encountered if a user bound to a role with any restrictions on authorized URLs tries to access the cost analyzer UI.
```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [x] The documentation is updated where needed.

### CODE REVIEW

**Review by gracedo — APPROVED** [review]
<3 this makes me so happy! Do you mind making the same change in yakcl? https://github.com/mesosphere/yakcl/blob/master/chart/kommander-federation/templates/federatedclusteraddon_kubecost.yaml#L43-L60

**Comment by gracedo** [comment]
Oh yeah, do we need/want this to go into this next GA release? If not, we can hold on this PR until after the release (since we'll want to get this into the next minor version bump for release after)

**Review by armandgrillet — APPROVED** [review]

**Review by hectorj2f — APPROVED** [review]

**Comment by armandgrillet** [comment]
We're gonna get this in the release as it impacts customers with and without airgapped clusters (it depends on the roles).

**Comment by armandgrillet** [comment]
@branden @gracedo yakcl PR: https://github.com/mesosphere/yakcl/pull/260

**Pull request merged**
