### PR TITLE
chore: bump karma to 1.5.0

### PR DESCRIPTION
**Pull request by d2iq-dispatch**
automated bumps for chore: bump karma to 1.5.0

### CODE REVIEW

**Comment by gracedo** [comment]
```
2021-03-17T22:04:59.974588862Z Save error occurred:  Dependency kommander-karma at version 0.4.0 does not satisfy the constraint 0.3.12
2021-03-17T22:04:59.974593110Z Deleting newly downloaded charts, restoring pre-update state
2021-03-17T22:05:00.007880801Z Error: Dependency kommander-karma at version 0.4.0 does not satisfy the constraint 0.3.12
```
hmm I guess it also needs to be bumped here https://github.com/mesosphere/charts/blob/master/stable/kommander/requirements.yaml#L3

**Comment by mhrabovcin** [comment]
Can we put this PR onhold. We have to use custom built `karma` version for unidirectional connections - https://github.com/mesosphere/charts/pull/1048

**Comment by mhrabovcin** [comment]
As part of unidirectional work we've added support for proxied requests to `karma`. This was now merged into the `master` code branch https://github.com/prymitive/karma/pull/2903.
We need to wait for the next karma release or backport this patch into the upgraded version. If we upgrade to a version without proxy support it will break the unidirectional feature.

**Review by mhrabovcin — CHANGES_REQUESTED** [review]
As part of unidirectional work we've added support for proxied requests to `karma`. This was now merged into the `master` code branch https://github.com/prymitive/karma/pull/2903.
We need to wait for the next karma release or backport this patch into the upgraded version. If we upgrade to a version without proxy support it will break the unidirectional feature.

**Pull request closed without merging**
