### PR TITLE
fix: remove logo and brand link

### PR DESCRIPTION
**Pull request by natmegs**
Remove branded assets on landing page.

### CODE REVIEW

**Comment by jaxesn** [comment]
nothing quite like reviewing minified html + css :shipit:

**Comment by alejandroEsc** [comment]
What happened to the html resource file page i created and why did we go back to using a line in the chart directly in the configmap? Also can you add me as a maintainer of this chart?

**Comment by s12chung** [comment]
@alejandroEsc I didn't see the `html resource file page` anywhere. this code is pretty much the same as the old manifest `kubeaddons-configs` code because it had some changes from the security team.

this code was written late last night and the landing is a temporary stopgap until we find a better solution.

**Comment by hectorj2f** [comment]
Please, rebase against `dev` we merged some changes

**Pull request merged**
