### PR TITLE
Bump kommander-ui in kommander & opsportal charts

### PR DESCRIPTION
**Pull request by brandonc**
Adds a redirect when you don't request a trailing slash

`/ops/portal` :arrow_right: `302 /ops/portal/`
`/ops/portal/kommander/ui` :arrow_right:  `302 /ops/portal/kommander/ui/`

While retaining the functionality of "PathPrefixStrip" for other paths

### CODE REVIEW

**Comment by juliangieseke** [comment]
lets also integrate #426 (KCL bump) before merging  🙇

**Comment by brandonc** [comment]
need to check on an issue concerning logout redirect

**Comment by brandonc** [comment]
@juliangieseke do you want to take a stab at converting these new rules to PathPrefixStripRegex type (https://docs.traefik.io/v1.4/basics/#matchers)? It has been speculated that the modifier we are using doesn't send this header https://github.com/mesosphere/traefik-forward-auth/blob/9291276945dde787f3f5866710cb1414e616aa8f/internal/auth.go#L87

If not, no worries that will be my priority tomorrow.

**Comment by jaxesn** [comment]
@juliangieseke skip this for now, I have been messing with this trying to fix it for the redirect case and cant get it to work. I'll look at it some more in the morning with brandon and if we cant figure it out we can bail on this for now.

**Comment by jaxesn** [comment]
Closing this one.

**Pull request closed without merging**
