### PR TITLE
replace deployment when upgrading

### PR DESCRIPTION
**Pull request by joejulian**
**What this PR does/ why we need it**:

The upstream cert-manager chart uses a dynamically generated label in
the selector. The selector is immutable so this fails when upgrading
from tiller to helm v3.

By forking and changing just the deployment name, the deployment will be
recreated using the new selector.

Since the goal is to retire the 0.10 version of cert-manager from our
products in the near future, this should not create an
undue maintenance burden.

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-70812

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by dkoshkin** [comment]
@joejulian can you split up the forking of cert-manager and the changes applied to it into 2 separate commits please.

**Comment by joejulian** [comment]
> @joejulian can you split up the forking of cert-manager and the changes applied to it into 2 separate commits please.

Good point, done.

**Comment by alejandroEsc** [comment]
shoot, i think we have to include crd management in this PR similar to velero.

**Comment by joejulian** [comment]
This will not pass e2e tests due to https://github.com/mesosphere/charts/blob/master/test/e2e-kind.sh#L284 installing cert-manager.

I have performed these tests, locally, commenting out that line and the tests pass.

**Review by shaneutt — APPROVED** [review]
We should take extra special care that we've manually tested this upgrade a few times (I think we already have I'm just being extra cautious) and then :heavy_check_mark: for merge

**Pull request merged**
