### PR TITLE
[release/kommander-0.8.x] Cherry-pick Makefile and Dispatchfile updates

### PR DESCRIPTION
**Pull request by gracedo**
Cherry-picks all the Makefile and Dispatchfile commits (including testing related ones.. essentially non-chart changes) that went in after kommander 0.8.x release branch was cut so that the publish script is up to date. I double checked that a `git diff master Makefile Dispatchfile` comes up with a blank diff. I also tested out a `make publish` off this branch on my fork of charts and verified that the publish script worked correctly and only published the 0.8.44 chart: see https://github.com/gracedo/charts/commit/aadd013fd0c93be20a8a5cfc0d36e4420c150887

### CODE REVIEW

**Comment by dkoshkin** [comment]
The removed lines like in [here](https://github.com/gracedo/charts/commit/aadd013fd0c93be20a8a5cfc0d36e4420c150887#diff-adff2fd64c62dd35156aa0b51f4d504dL2298-L2326), is that expected?

**Comment by gracedo** [comment]
@dkoshkin Hmmm good catch.... I'm not sure why those were removed, found https://github.com/fluxcd/helm-operator/issues/68 and looking more into it, maybe something to do with helm v2 vs v3, wonder if it's something to do with my machine running the script since I'm still on helm `v2.16.7` 🤔 I'll look into this more but meanwhile @joejulian have you seen anything like this in your helm-ing?

**Comment by joejulian** [comment]
I have not, but the Makefile _should_ be pulling and using its own helm.

**Comment by gracedo** [comment]
I downloaded helm v3.3.0 for use via `helmv3` on my local and re-ran the publish job but modified this line https://github.com/mesosphere/charts/pull/762/files#diff-b67911656ef5d18c4ae36cb6741b7965R33 `HELM := $(shell command -v helm)` to `HELM := $(shell command -v helmv3)` and this time the dependencies weren't removed; see https://github.com/gracedo/charts/commit/7a33c24b8e8390cd19b1c23ec50a24f00339b24b#diff-adff2fd64c62dd35156aa0b51f4d504dR726

**Comment by joejulian** [comment]
Makefile is only pulling its own helm if the binary is not in the path. :/

**Comment by gracedo** [comment]
@joejulian yep, let's get that fixed in another PR off master. for now to unblock the release I will merge in this PR and run publish on the release branch with the above one-liner change locally. there shouldn't be any surprises as the test run off my fork looks good https://github.com/gracedo/charts/commit/7a33c24b8e8390cd19b1c23ec50a24f00339b24b#diff-adff2fd64c62dd35156aa0b51f4d504dR726

**Pull request merged**
