### PR TITLE
awscsidriver: bump csi driver version

### PR DESCRIPTION
**Pull request by hectorj2f**

### CODE REVIEW

**Comment by hectorj2f** [comment]
I want to test this change to be sure we don't need it as part of the chart https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/a9a90b921310b8ad24460512b9829e961aff5549#diff-97777ab7d2c4944818065195f23faf0a

**Comment by shaneutt** [comment]
Hey team, it had just been a while since I saw any updates on this one: any help needed to move forward and/or get unblocked on this one?

**Comment by hectorj2f** [comment]
@shaneutt it needs some real testing... I might get some time early next week.

**Comment by hectorj2f** [comment]
Screen Shot 2019-09-23 at 5 02 01 PM
Screen Shot 2019-09-23 at 5 04 28 PM

**Pull request merged**
