### PR TITLE
Added a chart for github eventing source.

### PR DESCRIPTION
**Pull request by chhsia0**
We used a custom controller image to include the following fix:
https://github.com/knative/eventing-contrib/pull/489

JIRA: https://jira.mesosphere.com/browse/DCOS-56869

### CODE REVIEW

**Comment by joejulian** [comment]
please rebase against current `dev`

**Comment by chhsia0** [comment]
@joejulian Rebased and updated the README.

**Comment by shaneutt** [comment]
@chhsia0 this seems to be failing similarly to one of your parallel PRs:

https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2110471&_focus=476

Let us know if you need any assistance with this PR and we'll help out! :+1:

**Comment by chhsia0** [comment]
Fixed PTAL

**Pull request merged**
