### PR TITLE
Make GRPC and HTTP certificate creation non hook jobs.

### PR DESCRIPTION
**Pull request by tillt**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

Fixes deployments of dex with ```replicas > maxUnavailable```.

The helm charts repo is being deprecated; https://github.com/helm/charts#%EF%B8%8F-deprecation-and-archive-notice thus until there is an official chart repo for dex, we use a fork. 

**Which issue(s) this PR fixes**:

https://github.com/helm/charts/issues/24229
https://jira.d2iq.com/browse/D2IQ-72837

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by tillt** [comment]
I have tested an upgrade scenario manually as follows:
- forked KBA (https://github.com/tillt/charts)
- patched the KBA test sources according to @shaneutt with a patch that leaves `TestSsoGroup` up and running without cleaning up
- ran the test
- bumped forked dex chart to 2.9.1
- kubectl apply'ed the chart
- observed the dex addon getting updated
- observed the `kubeaddons-controller-manager` logs for any errors or weirdness

**Comment by tillt** [comment]
We are holding off with this until after the release, please!

**Comment by tillt** [comment]
> We are holding off with this until after the release, please!

We should be good now - please consider reviewing.

**Review by makkes — APPROVED** [review]

**Review by jr0d — APPROVED** [review]
lgmt, It might make sense to do this in a pre-install/upgrade hook to ensure that the secret is created before the pod is created. But, I think in this scenario, the pod will just crash loop until the secret is available.

**Pull request merged**
