### PR TITLE
Added a chart for knative-serving.

### PR DESCRIPTION
**Pull request by chhsia0**
The contents are retrieved from https://github.com/knative/serving/releases/download/v0.7.1/serving.yaml.
The YAML files are organized as in https://github.com/knative/serving/tree/master/config

JIRA: https://jira.mesosphere.com/browse/DCOS-56265

### CODE REVIEW

**Comment by joejulian** [comment]
please rebase against current dev

**Comment by chhsia0** [comment]
@joejulian Rebased. Also added a README. PTAL!

**Comment by chhsia0** [comment]
Seems I'm hitting this: https://github.com/helm/helm/pull/3987
TR;DR: dependencies on subcharts don't work w/ `helm dependency build`. Should I remove those enabling conditions for now?

**Comment by shaneutt** [comment]
@chhsia0 

>  TR;DR: dependencies on subcharts don't work w/ helm dependency build.
> Should I remove those enabling conditions for now?

Yes, but if this introduces any deficiencies that are acceptable to improve in later iterations, let's make sure we create TODO comments and JIRA cards for follow up. :+1:

**Comment by chhsia0** [comment]
JIRA for adding the options back: https://jira.mesosphere.com/browse/DCOS-57041

@shaneutt PTAL

**Comment by chhsia0** [comment]
@shaneutt Can you be more specific about the testing plan? I have tested the PR with my own cluster, and run some demo knative apps. Eventually I'd like to have a CI test for knative in konvoy.

**Comment by hectorj2f** [comment]
i believe we need a rebase against dev branch now

**Comment by shaneutt** [comment]
@hectorj2f ok to merge, or more to do?

**Comment by hectorj2f** [comment]
@shaneutt it is fine... but it needs to be rebased against `dev` again :)

**Pull request merged**
