### PR TITLE
[kommander] helm3 changes

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

This moves kommander into helm3, this is a breaking change hence the version

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
~~The helm2 test will and should fail intentionally. ~~ seems like we skip these tests. 

**Does this PR introduce a user-facing change?**:

```release-note
Kommander is now deployable by helm3 only
```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by alejandroEsc** [comment]
Note I will do the merging please.

**Comment by hectorj2f** [comment]
@alejandroEsc please, use the right label if you want to merge it.

**Comment by alejandroEsc** [comment]
> @alejandroEsc please, use the right label if you want to merge it yourself.

yeah i was looking for a "let me merge it" label, will create one.

**Pull request merged**
