### PR TITLE
MWT Bump

### PR DESCRIPTION
**Pull request by juliangieseke**
⚠️ trying to clarify https://github.com/mesosphere/kommander/pull/1798

commits: 
1. bump UI t fix routing issues (context: https://github.com/mesosphere/kommander/pull/1802 )
2. bumps KCL

### CODE REVIEW

**Comment by hectorj2f** [comment]
@juliangieseke can you bump KCL to v0.4.7 as part of this PR ?

**Comment by juliangieseke** [comment]
yup, 1sec

**Comment by juliangieseke** [comment]
> Error: could not find : chart kommander-cluster-lifecycle not found in https://mesosphere.github.io/kommander-cluster-lifecycle/charts

trying again in a couple min… docker not yet pushed?

**Comment by juliangieseke** [comment]
KCL is added. trying to figure out if https://github.com/mesosphere/kommander/pull/1798 is important

**Pull request merged**
