### PR TITLE
chore: test dispatch webhook

### PR DESCRIPTION
**Pull request by makkes**

### CODE REVIEW

**Comment by shaneutt** [comment]
This has been sitting for some time. Is it safe to close this PR, or is follow-up intended?

**Comment by makkes** [comment]
> This has been sitting for some time. Is it safe to close this PR, or is follow-up intended?

@shaneutt, thanks for looking into this. This PR is basically a showcase for Dispatch posting the wrong links in status checks, i.e. it posts the ELB address instead of the configured CNAME. As long as that's still happening, I'd like to keep this PR open to see whether anything changes on Dispatch side.

**Comment by shaneutt** [comment]
> > This has been sitting for some time. Is it safe to close this PR, or is follow-up intended?
> 
> @shaneutt, thanks for looking into this. This PR is basically a showcase for Dispatch posting the wrong links in status checks, i.e. it posts the ELB address instead of the configured CNAME. As long as that's still happening, I'd like to keep this PR open to see whether anything changes on Dispatch side.

Ok sounds good thanks for checking in :+1:

**Comment by shaneutt** [comment]
@makkes ping! should we pick this one back up, or close it?

**Comment by makkes** [comment]
thanks @shaneutt for the reminder. Closed it.

**Pull request closed without merging**
