### PR TITLE
[kommander-cluster ] initial contribution

### PR DESCRIPTION
**Pull request by alejandroEsc**
Initial contribution for a chart of the Kommander lifecycle github repo.

This is very prelim and there is much work yet to be done.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Thank you for starting this! Can we please get this moved to cluster lifecycle repo and ultimately added as chart dependency of kommander chart? What do you think?

**Comment by alejandroEsc** [comment]
> Thank you for starting this! Can we please get this moved to cluster lifecycle repo and ultimately added as chart dependency of kommander chart? What do you think?

I am not sure why it belong in cluster-lifecycle? Not saying I wont do it, just whats the reasoning exactly?

**Comment by jimmidyson** [comment]
@alejandroEsc This chart is specifically for deploying cluster lifecycle components. Cluster lifecycle currently uses kustomize for generating manifests and for deploying in both testing and development, which means we would have two different ways to deploy cluster lifecycle (kustomize and this chart) which would need to keep in sync, etc. By putting the chart in the cluster lifecycle repo, we can use the chart during development and testing, and ensure the chart remains up to date with changes as they are made by using controller-gen updates files, rather than having to manually make changes in this chart repo. When new versions of cluster lifecycle are released, the kommander chart dependency can be updated to use the latest version.

**Comment by alejandroEsc** [comment]
closing per request.

**Pull request closed without merging**
