### PR TITLE
kommander: Bump kubecost

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

chore

**What this PR does/ why we need it**:

bump kubecost to latest which includes massive perf improvements as well as some fixes to regression in prev version

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by joejulian — APPROVED** [review]

**Review by armandgrillet — APPROVED** [review]

**Review by hectorj2f — COMMENTED** [review]
Could we please align this bump with the bump in yakcl too https://github.com/mesosphere/yakcl/blob/master/chart/kommander-federation/templates/federatedclusteraddon_kubecost.yaml#L37 ?

**Review by jimmidyson — APPROVED** [review]

**Comment by jimmidyson** [comment]
@hectorj2f Can you raise a JIRA for that and assign it to @gracedo, if she doesn't mind picking it up?

**Comment by jimmidyson** [comment]
I' m going to merge this now.

**Comment by gracedo** [comment]
this was bumped in yakcl in this pr https://github.com/mesosphere/yakcl/pull/335

**Pull request merged**
