### PR TITLE
Merge in forks of stable charts from helm/charts

### PR DESCRIPTION
**Pull request by joejulian**
**What type of PR is this?**

chore

**What this PR does/ why we need it**:

The default helm charts are being retired by mid November. In order to support customers as we work toward a migration to using upstream charts we have decided to temporarily fork these charts from upstream.

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-72544

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by makkes — COMMENTED** [review]
Shouldn't these at least partly belong into `staging/`?

**Comment by joejulian** [comment]
> Shouldn't these at least partly belong into `staging/`?

I don't think so. This isn't a temporary fork that we're maintaining while waiting for our changes to be merged upstream. This particular upstream is going away. We need these charts moved in order to support our current customers on the KBA versions they already have installed.

**Review by alejandroEsc — APPROVED** [review]
Not blocking. This is a bit scary, im guessing that we are doing this and not squashing cause we are keeping the history as well. I am ok with this being in stable etc.. as it will be maintained until  we no longer have tools pointing to these charts.

**Comment by joejulian** [comment]
> ... not squashing cause we are keeping the history as well ...
Also, we do need to publish some previous versions so the legacy customers aren't interrupted.

**Review by dkoshkin — APPROVED** [review]

**Review by jr0d — APPROVED** [review]

**Pull request merged**
