### PR TITLE
feat: Bump kubecost to 1.91.0

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

feat

**What this PR does/ why we need it**:

bump kubecost to latest

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-86142

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by takirala — APPROVED** [review]

**Review by branden — APPROVED** [review]

**Review by cwyl02 — APPROVED** [review]

**Comment by gracedo** [comment]
Another test run failed on previous step deploying cert-manager
```
client.go:547: [debug] Add/Modify event for cert-manager-setup-certificaterequests-crd: MODIFIED
client.go:586: [debug] cert-manager-setup-certificaterequests-crd: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: failed pre-install: timed out waiting for the condition
helm.go:88: [debug] failed pre-install: timed out waiting for the condition
```

I think dispatch is very sloooooow right now. Gonna admin-merge this as it is a simple bump and will be tested in kommander

**Pull request merged**
