### PR TITLE
[kommander] Move  chart to kommander UI repo

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
I'm currently moving the UI parts of the kommander chart into our repo. I think this PR can be tested as is, but I would like to only merge it when the updates of our UI chart are automated (not against this repo, but against its gh-pages). PR for reference: https://github.com/mesosphere/kommander/pull/1418

### CODE REVIEW

**Comment by alejandroEsc** [comment]
please rebase, and could we see some output?

**Comment by DanielMSchmidt** [comment]
@alejandroEsc I tried applying it but I get this error and I'm not sure why, could you help me with debugging here?

```
helm install ./stable/kommander --set kommander-cluster-lifecycle.certificates.issuer.name=daniel --debug                                                                                                    306ms
[debug] Created tunnel using local port: '62100'

[debug] SERVER: "127.0.0.1:62100"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/danielschmidt/projects/charts/stable/kommander

Error: customresourcedefinitions.apiextensions.k8s.io "clusterpropagatedversions.core.kubefed.io" already exists
```

**Comment by alejandroEsc** [comment]
what is creating that CR? I would start a new kind cluster, and try to redeploy there. and see if that works out. However, let's find that crd first as it would mean we are not properly handling that resource and this would require some additional changes as it would mean future upgrades are blocked.

**Comment by DanielMSchmidt** [comment]
Forgot to update heute, that was just die to an installation attempt I aborted on that cluster. I have no idea if this works, because I could not install cert manager, which seems to be an implicit dependency

**Comment by DanielMSchmidt** [comment]
@alejandroEsc could you try the installation? I'm sure it's trivial for you 🙈

**Comment by alejandroEsc** [comment]
Hmmm.. Strange that error occurred, i double checked the tooling and so far it seems that crds are managed as expected. Anyway i was able to deploy:
```
helm install ./stable/kommander --name kommander-kubeaddons --namespace kubeaddons --set kommander-cluster-lifecycle.certificates.issuer.selfSigned=true
NAME:   kommander-kubeaddons
LAST DEPLOYED: Wed Jan 15 15:05:14 2020
NAMESPACE: kubeaddons
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                                      AGE
kcl-addon-update-watcher                  3s
kcl-admin                                 3s
kcl-cm                                    3s
kcl-edit                                  3s
kcl-rbac-proxy                            3s
kcl-tfcb                                  3s
kcl-view                                  3s
kcl-webhook                               3s
kommander-kubeaddons-grafana-clusterrole  3s
kommander-kubeaddons-kubeaddons-catalog   3s
kubefed-role                              3s
system:kubefed:admission-requester        3s

==> v1/ClusterRoleBinding
NAME                                             AGE
kcl-addon-update-watcher                         3s
kcl-cm                                           3s
kcl-rbac-proxy                                   3s
kcl-tfcb                                         3s
kcl-webhook                                      3s
kcl-webhook:auth-delegator                       3s
kommander-kubeaddons-grafana-clusterrolebinding  3s
kommander-kubeaddons-kommander-ui                3s
kommander-kubeaddons-kubeaddons-catalog          3s
kubefed-admission-webhook:anonymous-auth         3s
kubefed-admission-webhook:auth-delegator         3s
kubefed-rolebinding                              3s

==> v1/ConfigMap
NAME                                                   AGE
kommander-kubeaddons-grafana                           3s
kommander-kubeaddons-grafana-config-dashboards         3s
kommander-kubeaddons-grafana-test                      3s
kommander-kubeaddons-k8s-resources-clusters-dashboard  3s
kommander-kubeaddons-thanosquery-dashboard             3s

==> v1/Deployment
NAME                                     AGE
kcl-cm                                   2s
kcl-tfcb                                 2s
kcl-utility-apiserver                    2s
kcl-webhook                              2s
kommander-kubeaddons-grafana             2s
kommander-kubeaddons-karma               2s
kommander-kubeaddons-kommander-ui        2s
kommander-kubeaddons-kubeaddons-catalog  2s
kommander-kubeaddons-thanos-query        2s
kubefed-admission-webhook                2s
kubefed-controller-manager               2s

==> v1/Namespace
NAME              AGE
kommander-system  3s

==> v1/Pod(related)
NAME                                                      AGE
kcl-cm-5d6c65f5df-wtwhl                                   2s
kcl-tfcb-6b98cd5997-wbf4z                                 2s
kcl-utility-apiserver-78dc6964db-669ws                    2s
kcl-webhook-6ffbdb5c78-pq4p5                              2s
kommander-kubeaddons-grafana-5bc4cc779d-7h2mf             2s
kommander-kubeaddons-karma-68fcb69494-phrx5               2s
kommander-kubeaddons-kommander-ui-7cdf884fcf-6njm7        2s
kommander-kubeaddons-kubeaddons-catalog-7df9885bff-msqld  2s
kommander-kubeaddons-thanos-query-5bd88795c5-ls28j        2s
kubefed-admission-webhook-7fdcc5b56f-xt67v                2s
kubefed-controller-manager-75bdd8c787-98ft7               2s
kubefed-controller-manager-75bdd8c787-txcgm               2s

==> v1/ResourceQuota
NAME                     AGE
one-license-per-cluster  3s

==> v1/Role
NAME                               AGE
kcl-leader-election                3s
kommander-kubeaddons-grafana-test  3s
kubefed-admission-webhook-role     3s
kubefed-config-role                3s

==> v1/RoleBinding
NAME                                           AGE
kcl-leader-election                            2s
kcl-webhook:authentication-reader              2s
kommander-kubeaddons-grafana-test              2s
kubefed-admission-webhook-rolebinding          2s
kubefed-admission-webhook:apiextension-viewer  2s
kubefed-config-rolebinding                     2s

==> v1/Secret
NAME                                    AGE
kommander-karma-client-tls              3s
kommander-kubeaddons-grafana            3s
kommander-thanos-client-tls             3s
kubefed-admission-webhook-serving-cert  3s

==> v1/Service
NAME                                     AGE
kcl-cm-metrics                           2s
kcl-tfcb                                 2s
kcl-utility-apiserver                    2s
kcl-webhook                              2s
kommander                                2s
kommander-kubeaddons-grafana             2s
kommander-kubeaddons-karma               2s
kommander-kubeaddons-kubeaddons-catalog  2s
kommander-kubeaddons-thanos-query-grpc   2s
kommander-kubeaddons-thanos-query-http   2s
kubefed-admission-webhook                2s

==> v1/ServiceAccount
NAME                               AGE
kcl-addon-update-watcher           3s
kcl-cm                             3s
kcl-tfcb                           3s
kcl-webhook                        3s
kommander-kubeaddons-grafana       3s
kommander-kubeaddons-grafana-test  3s
kommander-kubeaddons-karma         3s
kubefed-admission-webhook          3s
kubefed-controller                 3s

==> v1alpha1/Certificate
NAME                       AGE
kcl-tfcb-tls               2s
kcl-utility-apiserver-tls  2s
kcl-webhook-tls            2s

==> v1alpha1/Issuer
NAME            AGE
kcl-selfsigned  2s

==> v1beta1/APIService
NAME                                     AGE
v1beta1.webhook.kommander.mesosphere.io  2s

==> v1beta1/CronJob
NAME                      AGE
kcl-addon-update-watcher  2s

==> v1beta1/FederatedAddon
NAME                                        AGE
dashboard-kommander-override                2s
kommander-kubeaddons-kommander-karma-proxy  2s
kommander-kubeaddons-kommander-thano-proxy  2s
kube-oidc-proxy-kommander                   2s
opsportal-addons-kommander-overrides        2s
traefik-forward-auth-kommander              2s

==> v1beta1/FederatedClusterRole
NAME                     AGE
kommander-admin          2s
kommander-cluster-admin  2s
kommander-edit           2s
kommander-view           2s

==> v1beta1/FederatedClusterRoleBinding
NAME                                                 AGE
kubeaddons-controller-manager-cluster-admin-binding  2s
ops-portal-user-kommander                            2s

==> v1beta1/FederatedCustomResourceDefinition
NAME                                    AGE
addons.kubeaddons.mesosphere.io         2s
clusteraddons.kubeaddons.mesosphere.io  2s

==> v1beta1/FederatedDeployment
NAME                           AGE
kubeaddons-controller-manager  2s

==> v1beta1/FederatedNamespace
NAME              AGE
kommander-system  2s
kubeaddons        2s

==> v1beta1/FederatedSecret
NAME                                              AGE
kommander-kubeaddons-kommander-karma-server-tls   2s
kommander-kubeaddons-kommander-thanos-server-tls  2s

==> v1beta1/FederatedServiceAccount
NAME                           AGE
kubeaddons-controller-manager  2s

==> v1beta1/FederatedTypeConfig
NAME                                            AGE
addons.kubeaddons.mesosphere.io                 2s
addonsdeployments.kubeaddons.mesosphere.io      2s
clusteraddons.kubeaddons.mesosphere.io          2s
clusterrolebindings.rbac.authorization.k8s.io   2s
clusterroles.rbac.authorization.k8s.io          2s
configmaps                                      2s
customresourcedefinitions.apiextensions.k8s.io  2s
deployments.apps                                2s
ingresses.extensions                            2s
jobs.batch                                      2s
namespaces                                      2s
replicasets.apps                                2s
rolebindings.rbac.authorization.k8s.io          2s
roles.rbac.authorization.k8s.io                 2s
secrets                                         2s
serviceaccounts                                 2s
services                                        2s

==> v1beta1/Ingress
NAME                                             AGE
kommander-kubeaddons-grafana                     2s
kommander-kubeaddons-karma                       2s
kommander-kubeaddons-kommander-ui                2s
kommander-kubeaddons-kubeaddons-catalog-ingress  2s
kommander-kubeaddons-thanos-query-http           2s

==> v1beta1/KubeFedConfig
NAME     AGE
kubefed  2s

==> v1beta1/MutatingWebhookConfiguration
NAME                      AGE
kcl-defaulting            2s
mutation.core.kubefed.io  2s

==> v1beta1/PodSecurityPolicy
NAME                               AGE
kommander-kubeaddons-grafana       3s
kommander-kubeaddons-grafana-test  3s

==> v1beta1/Role
NAME                          AGE
kommander-kubeaddons-grafana  3s

==> v1beta1/RoleBinding
NAME                          AGE
kommander-kubeaddons-grafana  2s

==> v1beta1/ValidatingWebhookConfiguration
NAME                         AGE
kcl-validating               2s
validations.core.kubefed.io  2s

```

however deleting seems to fail
```$ helm delete --purge kommander-kubeaddons
Error: timed out waiting for the condition```

and that is due to 
```
$ ka logs -f karma-configmap-cleanup-bhdjv
Error from server (Forbidden): configmaps "kommander-kubeaddons-config" is forbidden: User "system:serviceaccount:kubeaddons:kommander-kubeaddons" cannot delete resource "configmaps" in API group "" in the namespace "kubeaddons"
```

but I do not think that is covered in this PR.

**Comment by alejandroEsc** [comment]
please rebase.

**Comment by DanielMSchmidt** [comment]
@alejandroEsc rebased 👍

**Pull request merged**
