### PR TITLE
chore: bump kubeaddons-catalog chart to latest release

### PR DESCRIPTION
**Pull request by makkes**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

Bump kubeaddons-catalog to latest app version

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-72080

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Kommander Catalog does show items again after not having shown any items in earlier versions.
```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by armandgrillet — APPROVED** [review]
LGTM

**Review by shaneutt — APPROVED** [review]

**Comment by shaneutt** [comment]
This should be manually tested prior to merging, as we have limited testing in place for Kommander catalog.

**Comment by makkes** [comment]
@shaneutt any hunch why the checks are not kicking off?

**Comment by shaneutt** [comment]
> @shaneutt any hunch why the checks are not kicking off?

build configuration in TC is all paused @alejandroEsc / @joejulian  are we 100% on dispatch now for charts?

**Pull request merged**
