### PR TITLE
dispatch: add v0.3.0 chart

### PR DESCRIPTION
**Pull request by gpaul**

### CODE REVIEW

**Comment by gpaul** [comment]
The `ct.lint` task fails with:
```
Save error occurred:  directory staging/dispatch/charts/argo-cd not found
```

Presumably due to the "local" chart repository not running:
```
Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
```

Any ideas?

**Comment by gpaul** [comment]
@shaneutt @joejulian perhaps?

**Comment by gpaul** [comment]
This may be due to 
```
dependencies:
  - name: argo-cd
    version: "0.4.0"
    repository: "file://charts/argo-cd"
    condition: argo-cd.enabled
```
In the ./staging/dispatch/requirements.yaml file

**Comment by gpaul** [comment]
@shaneutt @joejulian I had to remove the requirements.yaml file from the new ./staging/dispatch chart in order to get CI to pass.

**Comment by jbarrick-mesosphere** [comment]
@joejulian / @shaneutt can we push this over the finish line?

**Comment by jbarrick-mesosphere** [comment]
@joejulian / @shaneutt We have approvals, but I'm not able to merge. Who can merge this?

**Pull request merged**
