### PR TITLE
[kommander] crd fix (part 1)

### PR DESCRIPTION
**Pull request by alejandroEsc**
This PR is following the solution to fixing crd installation problems encountered when trying to deploy/upgrade a chart given existing crds. It also functionally attempts to update crds if so required. 

part 1 of 2. Second part would include pulling in a new kubefed chart that contains fixes for those CRDs.

### CODE REVIEW

**Comment by jimmidyson** [comment]
We can get rid of observable cluster, confirmed with UI team.

**Comment by alejandroEsc** [comment]
> We can get rid of observable cluster, confirmed with UI team.

awesome, if that is the case let me update the chart.

**Comment by jimmidyson** [comment]
I think we can also get rid of the separate enablement of different federated resources, they should always all be enabled.

**Comment by alejandroEsc** [comment]
> I think we can also get rid of the separate enablement of different federated resources, they should always all be enabled.

sounds ok, i will do so in a follow pr

**Pull request merged**
