### PR TITLE
fix: override cert-manager release name to work with hardcoded values in CRD files

### PR DESCRIPTION
**Pull request by jr0d**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

Override cert-manager release name to work with hard coded values in CRD files.
**Which issue(s) this PR fixes**:

no issue

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
[cert-manager] 
```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by dkoshkin — APPROVED** [review]
These changes look good, I haven't looked if there are others though.

**Review by samvantran — COMMENTED** [review]
Looks good but the PR title and description says `use template variables for webhook names` but the code seems to be using hardcoded values instead?

**Comment by joejulian** [comment]
I think this needs to be done the other way around. Make the webhook  use the fixed name. As it is, if the name is changed in the addon, this will break again. If the webhook always uses a fixed name and is referenced by that same name everywhere, then it won't.

This is ok because we can only ever have cert-manager installed just once.

**Review by joejulian — CHANGES_REQUESTED** [review]
I'm afraid that this needs to be done the other way around. Make the webhook use the fixed name. As it is, if the name is changed in the addon, this will break again. If the webhook always uses a fixed name and is referenced by that same name everywhere, then it won't.

This is ok because we can only ever have cert-manager installed just once.

**Comment by jr0d** [comment]
@joejulian i went this route because the web hook not working just means we lose v1beta2 support, but sill allow names to be generated. I'll change it, when I get home.

**Review by joejulian — APPROVED** [review]

**Review by joejulian — APPROVED** [review]

**Comment by joejulian** [comment]
Approved, but needs a chart version bump.

**Review by alejandroEsc — APPROVED** [review]
Yeah we discussed this, lgtm. yuck.

**Review by samvantran — APPROVED** [review]

**Pull request merged**
