### PR TITLE
Consolidate storage provisioners in 'storageclasses' chart

### PR DESCRIPTION
**Pull request by nfnt**
Instead of using separate charts for different storage provisioners,
the 'storageclasses' charts is used to configure all storage provisioners
of a konvoy cluster. Subcharts are used for the respective provisioners.

### CODE REVIEW

**Comment by nfnt** [comment]
CI failure looks like https://github.com/helm/helm/issues/2247, i.e. `helm dependency build` doesn't work with subcharts.

**Comment by hectorj2f** [comment]
@nfnt tests are failing :/

**Comment by nfnt** [comment]
See above, this is due to https://github.com/helm/helm/issues/2247.

**Comment by nfnt** [comment]
We decided to go ahead with this solution, but need support for custom values that are specific for each provisioner first. This is to ensure that, e.g., on AWS the `awsebscsiprovisioner` plugin is set up as default storage class. @joejulian Is there a JIRA and/or PR to follow this work?

**Comment by shaneutt** [comment]
@joejulian just wanted to ping you on this one again as we need your input to proceed.

**Comment by nfnt** [comment]
Closing, as we've added [multiple storage classes support to `localvolumeprovisioner`](https://github.com/mesosphere/charts/pull/118) instead.

**Pull request closed without merging**
