### PR TITLE
Ensure kommander frontend is served

### PR DESCRIPTION
**Pull request by DanielMSchmidt**

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@s12chung Can you help me find the logs of the run in CI? I wanted to see that it really worked 😇

**Comment by s12chung** [comment]
i don't believe our ci runs in this repo actually runs the helm test.... all it does is lint. i trust that you ran it locally?

if we want to add helm tests to this repo, i believe helm charts uses this tool: https://github.com/helm/chart-testing

**Comment by DanielMSchmidt** [comment]
Nope, didn't ran it locally, because I trusted CI to run it.
Would it be a reasonable thing to add in this PR? And where do I change the CI configuration?

**Comment by s12chung** [comment]
I'd think it's reasonable to add it to this PR, as your existing code can be the "1st helm test" to test the helm test CI infrastructure.

add a new make target in the makefile. then configure teamcity to run the make target appropriate. the current makefile seems to use https://github.com/helm/chart-testing already, as `ct`: https://github.com/mesosphere/charts/blob/dev/Makefile#L87

**Comment by shaneutt** [comment]
This PR has been open for some time, but I also see a push from some days ago. Do you need any assistance from @mesosphere/sig-ksphere-catalog on this one @DanielMSchmidt to get it into `ready` state? Just let us know how we can help!

**Comment by DanielMSchmidt** [comment]
@shaneutt okay, I give up. I don't understand why the CI fails. The logs of the kommander UI backend seems to be okay, so it should be up.

**Comment by shaneutt** [comment]
> @shaneutt okay, I give up. I don't understand why the CI fails. The logs of the kommander UI backend seems to be okay, so it should be up.

@joejulian and/or @mesosphere/sig-ksphere-catalog anyone have some cycles to help with the CI issues here?

**Comment by shaneutt** [comment]
@joejulian do you have any time to help with this one today? If not, I think we should make a JIRA so it doesn't fall behind any further.

**Comment by shaneutt** [comment]
@DanielMSchmidt in my review, it seems that this chart has since had several updates that make these updates potentially very out of sync, I just want to verify: do you still need this PR?

**Comment by shaneutt** [comment]
It seems like this PR has become very stale, and significantly out of date with the source. I'm going to retain the branch but close the PR for now as there doesn't seem to be any review action that can currently be taken, please feel free to re-open this at any time to continue and let us know if you need any assistance!

**Pull request closed without merging**
