### PR TITLE
use existing storage config if it already exists

### PR DESCRIPTION
**Pull request by joejulian**
**What type of PR is this?**

bug

**What this PR does/ why we need it**:

If either prometheus or alertmanager resources exist and have a storage
attribute defined in their spec, reuse that instead of what's defined
in the values.

This prevents the accidental redefinition of the volumeClaimTemplate and
the abaondomnet of old data.

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/COPS-6870

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixed an upgrade issue where upgrading from a prior chart version that had a bug where the desired PVC name prefix was being discarded. This bug caused upgrades from that version to create and use new storage claims instead of the existing ones. This feature will now always use the storage setting defined in the cluster, if there is one, reusing the existing claims.
```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by joejulian** [comment]
Upgrade:
```
(mesosphere/charts@d1c73bd)$ helm install prometheus-kubeaddons staging/prometheus-operator --values /tmp/prometheus-values-3.0.1.yaml
```
```
(mesosphere/charts@d1c73bd)$ kubectl get pvc
NAME                                                                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-prometheus-kubeaddons-prom-prometheus-db-prometheus-prometheus-kubeaddons-prom-prometheus-0   Bound    pvc-246af7d8-a980-42d8-ae60-31f3862ccd59   50Gi       RWO            standard       13m
```
```
(mesosphere/charts@joe/promup)$ helm upgrade prometheus-kubeaddons staging/prometheus-operator --values /tmp/prometheus-values-3.3.0.yaml
...
NOTES:

NOTICE: A Prometheus resource was already defined. Retaining the existing storage definition.
If this is not the desired behavior, delete the prometheus-kubeaddons-prom-prometheus prometheus resource from the default namespace and upgrade this helm release.

prometheus-operator has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=prometheus-kubeaddons"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
```
```
(mesosphere/charts@joe/promup)$ kubectl get pvc
NAME                                                                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-prometheus-kubeaddons-prom-prometheus-db-prometheus-prometheus-kubeaddons-prom-prometheus-0   Bound    pvc-246af7d8-a980-42d8-ae60-31f3862ccd59   50Gi       RWO            standard       16m

```

**Review by gracedo — APPROVED** [review]
Lgtm, thanks so much for fixing all the patch scripts and upgrading too! 🙏

**Comment by gracedo** [comment]
Moving the job to `kubectl apply` the updated crds (including prometheus/alertmanager which added new fields) from pre-install to post-install fixed the broken upgrade validation errors. Essentially this follows the wise advice from a certain @joejulian out in the wild ;)

https://github.com/prometheus-community/helm-charts/issues/557#issuecomment-801490982
> You shouldn't _have_ to delete CRDs. Deleting CRDs deletes any defined resources that use that CRD and, in a cluster with more than one user, causes great consternation when you delete everybody's alerts and metrics.
> 
> CRDs have a **_version_** in order to provide a contract with the user. Had the CRD version been bumped, the chart templates could have tested against that version (`.Capabilities.APIVersions.Has "prometheus.monitoring.coreos.com/v1"`) and enabled or disabled fields as appropriate for the contract. The solution for the future is to honor that contract and not go changing charts to insert fields when you have no way of knowing if the field is even there. Use proper API version management.
> 
> For cli users, you can work around this by just applying the CRDs in the charts `crds/` directory using kubectl:
> 
> ```shell
> kubectl apply -f crds/
> ```
> 
> For the rest of us using gitops for continuous deployment, we're just out of luck.

Verified on kind cluster. Post-upgrade, just the one pvc remains and is reused, a new pvc does not get created:
```
Release "prometheus-kubeaddons" has been upgraded. Happy Helming!
NAME: prometheus-kubeaddons
LAST DEPLOYED: Mon Apr  5 20:31:53 2021
NAMESPACE: default
STATUS: deployed
REVISION: 2
NOTES:
NOTICE: A Prometheus resource was already defined. Retaining the existing storage definition.
If this is not the desired behavior, delete the prometheus-kubeaddons-prom-prometheus prometheus resource from the default namespace and upgrade this helm release.

$ k get pvc
NAME                                                                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-prometheus-kubeaddons-prom-prometheus-db-prometheus-prometheus-kubeaddons-prom-prometheus-0   Bound    pvc-3d4a861e-e908-4f1e-b9b5-cedd78cb2bd4   50Gi       RWO            standard       13m

```

**Review by hectorj2f — APPROVED** [review]

**Pull request merged**
