### PR TITLE
[kube-prometheus-stack] fix: grafana view only permissions

### PR DESCRIPTION
**Pull request by cwyl02**
**What type of PR is this?**
Bug

**What this PR does/ why we need it**:
Grafana view only role is missing certain nonResourceUrls and will get access denied on viewing dashboard 

**Which issue(s) this PR fixes**:
https://jira.d2iq.com/browse/D2IQ-84281

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by cwyl02** [comment]
error: timed out waiting for the condition on deployments/reloader-reloader 😅

**Review by gracedo — APPROVED** [review]

**Pull request merged**
