### PR TITLE
[elasticsearch] ES changes to deploy 7.10

### PR DESCRIPTION
**Pull request by alejandroEsc**
chart changes to create a 7.10 cluster

**What type of PR is this?**

CHORE

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-72964

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by alejandroEsc** [comment]
Not clear to me why locally tests pass but in CI tests seem to time out fail. Would like to get some more eyes on this please.

**Comment by s12chung** [comment]
for helm3, there was a timeout waiting for the init container, `plugin-install-ingest-attachment`:

```
2021-01-20T08:29:32.310975733Z   plugin-install-ingest-attachment:
2021-01-20T08:29:32.310978142Z     Container ID:  containerd://7ae49f2bb01b614f3ac94e98c4cf534f865aec555a77c7feac198ecf2134bd93
2021-01-20T08:29:32.310982718Z     Image:         docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1
2021-01-20T08:29:32.310985486Z     Image ID:      docker.elastic.co/elasticsearch/elasticsearch-oss@sha256:d37649ee302b82d4d37757a1e1462f815650bd410dbb6927937d7b4e5e3985ab
2021-01-20T08:29:32.310988051Z     Port:          <none>
2021-01-20T08:29:32.310990704Z     Host Port:     <none>
2021-01-20T08:29:32.310993299Z     Command:
2021-01-20T08:29:32.310995586Z       /bin/bash
2021-01-20T08:29:32.310997902Z     Args:
2021-01-20T08:29:32.311000132Z       -c
2021-01-20T08:29:32.311005740Z       yes | /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-attachment
2021-01-20T08:29:32.311009523Z     State:          Running
2021-01-20T08:29:32.311013082Z       Started:      Wed, 20 Jan 2021 08:19:55 +0000
2021-01-20T08:29:32.311016233Z     Ready:          False
2021-01-20T08:29:32.311018467Z     Restart Count:  0
2021-01-20T08:29:32.311020852Z     Environment:    <none>
2021-01-20T08:29:32.311023123Z     Mounts:
2021-01-20T08:29:32.311025538Z       /var/run/secrets/kubernetes.io/serviceaccount from elasticsearch-dee6cqw58z-master-token-sqtv4 (ro)
```

```
2021-01-20T08:29:32.554411834Z >>> kubectl logs elasticsearch-dee6cqw58z-master-0 --namespace elasticsearch-dee6cqw58z --container plugin-install-ingest-attachment
2021-01-20T08:29:32.638928129Z -> Installing ingest-attachment
2021-01-20T08:29:32.640633922Z ------------------------------------------------------------------------------------------------------------------------
2021-01-20T08:29:32.640652512Z <== Logs of init container elasticsearch-dee6cqw58z-master-0
2021-01-20T08:29:32.640658172Z ------------------------------------------------------------------------------------------------------------------------
2021-01-20T08:29:32.640662643Z ------------------------------------------------------------------------------------------------------------------------
2021-01-20T08:29:32.640666259Z ==> Logs of init container elasticsearch-dee6cqw58z-master-0
2021-01-20T08:29:32.640670135Z ------------------------------------------------------------------------------------------------------------------------
2021-01-20T08:29:32.640675171Z >>> kubectl logs elasticsearch-dee6cqw58z-master-0 --namespace elasticsearch-dee6cqw58z --container plugin-install-mapper-size
2021-01-20T08:29:32.727396723Z Error from server (BadRequest): container "plugin-install-mapper-size" in pod "elasticsearch-dee6cqw58z-master-0" is waiting to start: PodInitializing
2021-01-20T08:29:32.727483302Z Error printing details: Error waiting for process: exit status 1
2021-01-20T08:29:32.727491229Z >>> kubectl get pods elasticsearch-dee6cqw58z-master-0 --no-headers --namespace elasticsearch-dee6cqw58z --output jsonpath={.spec.containers[*].name}
2021-01-20T08:29:32.799744714Z ------------------------------------------------------------------------------------------------------------------------
2021-01-20T08:29:32.799773588Z ==> Logs of container elasticsearch-dee6cqw58z-master-0
2021-01-20T08:29:32.799779488Z ------------------------------------------------------------------------------------------------------------------------
2021-01-20T08:29:32.799783671Z >>> kubectl logs elasticsearch-dee6cqw58z-master-0 --namespace elasticsearch-dee6cqw58z --container elasticsearch
2021-01-20T08:29:32.889505184Z Error from server (BadRequest): container "elasticsearch" in pod "elasticsearch-dee6cqw58z-master-0" is waiting to start: PodInitializing
2021-01-20T08:29:32.889530268Z Error printing details: Error waiting for process: exit status 1
```

**Comment by s12chung** [comment]
for helm2 it 's the `plugin-install-mapper-size` init container.

for both, the timeouts are probably too short. maybe a bandwidth problem

**Comment by alejandroEsc** [comment]
> for helm2 it 's the `plugin-install-mapper-size` init container.
> 
> for both, the timeouts are probably too short. maybe a bandwidth problem

thanks @s12chung thats exactly what i was seeing and thinking, we never really tested this here i think @joejulian is it ok to ignore/delete these test and maybe bring them back later?

**Review by gracedo — APPROVED** [review]

**Review by branden — APPROVED** [review]

**Pull request merged**
