### PR TITLE
bug: fix gatekeeper pod mutations

### PR DESCRIPTION
**Pull request by s12chung**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

applyTo does not accept *, see https://open-policy-agent.github.io/gatekeeper/website/docs/mutation#extent-of-changes

**Which issue(s) this PR fixes**:

no issue, but part of a new feature for D2IQ-70021

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE, since these changes aren't user facing yet.
```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by gracedo — APPROVED** [review]

**Comment by joejulian** [comment]
Well... I guess there is nothing but v1 pods, but why does this matter?

**Comment by s12chung** [comment]
@joejulian with the old code, the mutation webhook won't do anything.

since they're release an rc, might as well add it to this PR later tonight too.

**Comment by alejandroEsc** [comment]
> @joejulian with the old code, the mutation webhook won't do anything.
> 
> since they're release an rc, might as well add it to this PR later tonight too.

What does this mean exactly? Granted it probably wont matter at this point, however we do want to mutate all pod versions right?

**Comment by s12chung** [comment]
@alejandroEsc yeah, we want to mutate all pod version, but the `*` syntax isn't accepted by gatekeeper (no validation error, but it doesn't work and the docs say it won't work either), so we're making due with `v1` instead.

**Comment by alejandroEsc** [comment]
> @alejandroEsc yeah, we want to mutate all pod version, but the `*` syntax isn't accepted by gatekeeper (no validation error, but it doesn't work and the docs say it won't work either), so we're making due with `v1` instead.
> 
> was testing with the new gatekeeper tag and discovered this.

At this point you are the expert, this was working with the new version so could you please add a comment on those places you are making a change so we know historically why we are setting it to v1, that way in the future we have a good idea if we ever want to switch back to "*"

**Comment by s12chung** [comment]
> add a comment on those places you are making a change so we know historically why we are setting it to v1

done.

**Comment by s12chung** [comment]
btw, I suspect it was working before because of the bug.

**Comment by alejandroEsc** [comment]
> btw, I suspect it was working before because of the bug that we're waiting the new version to patch.

lol yeah i bet. This has been a headache but what do you expect on v1alpha1 rigth? Anyway thank you for being on top of it.

**Comment by s12chung** [comment]
Lol yeah, didn't notice the v1alpha1 until after finding the fix. No worries! Enjoy your time off :)

**Review by armandgrillet — APPROVED** [review]
LGTM, thanks for the provided explanation.

**Pull request merged**
