### PR TITLE
[D2IQ-65734] add konvoy-async-auth chart

### PR DESCRIPTION
**Pull request by shaneutt**
As per [D2IQ-65734](https://jira.d2iq.com/browse/D2IQ-65734)

### CODE REVIEW

**Comment by shaneutt** [comment]
Blocked on https://github.com/mesosphere/konvoy-async-auth/pull/2 and [D2IQ-65269](https://jira.d2iq.com/browse/D2IQ-65269)

**Comment by jr0d** [comment]
@shaneutt should we move this to staging?

**Comment by shaneutt** [comment]
> @shaneutt should we move this to staging?

Originally we had intended staging for charts that we wanted to eventually send upstream :thinking: but I suppose it's more become a place where we put new charts. We don't have any real process in place right now to graduate charts one way or the other so I'm tempted to just keep it here but I'm open to suggestions. cc @joejulian

**Comment by joejulian** [comment]
https://github.com/mesosphere/charts/blob/master/README.md#repository-structure

**Comment by shaneutt** [comment]
we've changed course and decided we're not going to make a separate helm chart for this.

**Pull request closed without merging**
