### PR TITLE
kommander: bump version

### PR DESCRIPTION
**Pull request by hectorj2f**
Signed-off-by: Hector Fernandez <hectorj@gmail.com>

**What type of PR is this?**

chore
**What this PR does/ why we need it**:

Bump version to get fixes for a COPS ticket.
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by armandgrillet — APPROVED** [review]
LGTM.

**Comment by pierrebeitz** [comment]
here's a recent bump from rodney: https://github.com/mesosphere/charts/pull/1111

looks like we're missing changes to `stable/kommander/requirements.yaml` in here. also a lot of changes have conflicts. you may want to rebase that on master.

**Review by tillt — APPROVED** [review]

**Comment by hectorj2f** [comment]
@pierrebeitz Yep, the recent bump didn't include these changes.

I fixed the conflicts, there was an issue on my end when using git.

**Comment by gracedo** [comment]
superceded by https://github.com/mesosphere/charts/pull/1119

**Pull request closed without merging**
