### PR TITLE
feat: Bump kubecost to 1.99.0

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

feat

**What this PR does/ why we need it**:

bump kubecost to latest

**Which issue(s) this PR fixes**:

- https://d2iq.atlassian.net/browse/D2IQ-94465
- https://d2iq.atlassian.net/browse/D2IQ-94277

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by gracedo** [comment]
Not really understanding why the linter is failing after the recent dka bump (which bumped the chart version to 1.2.14):
```
>>> git diff --find-renames --name-only 549a5a07335876762525001d123cefbba2bb8d0c -- stable staging

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 dex-k8s-authenticator => (version: "1.2.14", path: "staging/dex-k8s-authenticator")
------------------------------------------------------------------------------------------------------------------------

>>> helm dependency build staging/dex-k8s-authenticator
Linting chart "dex-k8s-authenticator => (version: \"1.2.14\", path: \"staging/dex-k8s-authenticator\")"
Checking chart "dex-k8s-authenticator => (version: \"1.2.14\", path: \"staging/dex-k8s-authenticator\")" for a version bump...
>>> git cat-file -e origin/master:staging/dex-k8s-authenticator/Chart.yaml
>>> git show origin/master:staging/dex-k8s-authenticator/Chart.yaml
Error: failed linting charts: failed processing charts
Old chart version: 1.2.14
New chart version: 1.2.14
------------------------------------------------------------------------------------------------------------------------
 ✖︎ dex-k8s-authenticator => (version: "1.2.14", path: "staging/dex-k8s-authenticator") > chart version not ok. Needs a version bump! 
------------------------------------------------------------------------------------------------------------------------
failed linting charts: failed processing charts
make: *** [Makefile:161: ct.lint] Error 1
Error: Process completed with exit code 2.
```

I'll just bump the chart version again to get past it. It's failing on main

**Comment by gracedo** [comment]
Reverted, seeing same error - looks like the linter is looking at the wrong commit 
`git diff --find-renames --name-only 549a5a07335876762525001d123cefbba2bb8d0c -- stable staging`

That commit is not the latest commit on main, it points to the commit before the dka bump 🤔 
```
commit 088fc8ad63702d19e3d8da36f715f1afae2c63e5 (upstream/master, origin/master, master)
Author: Jonathan Juares Beber <jonathanbeber@gmail.com>
Date:   Wed Dec 7 18:01:05 2022 -0300

    fix: stop reencoding HMAC secret (#1384)

    Co-authored-by: Jimmi Dyson <jimmidyson@gmail.com>

 staging/dex-k8s-authenticator/Chart.yaml                 | 2 +-
 staging/dex-k8s-authenticator/templates/secret_hmac.yaml | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

commit 549a5a07335876762525001d123cefbba2bb8d0c
Author: Tarun Gupta Akirala <takirala@users.noreply.github.com>
Date:   Wed Dec 7 08:13:15 2022 -0800

    chore: pin image versions in knative chart (#1386)

    * chore: pin image versions in knative chart
    * chore: pin autoscaler-hpa image
    * chore: pin more images

    Signed-off-by: Tarun Gupta Akirala <takirala@users.noreply.github.com>

 staging/knative/Chart.yaml                                 |  4 ++--
 staging/knative/charts/serving/Chart.yaml                  |  2 +-
 staging/knative/charts/serving/templates/net-istio.yaml    |  4 ++--
 staging/knative/charts/serving/templates/serving-core.yaml | 17 ++++++++---------
 staging/knative/charts/serving/templates/serving-hpa.yaml  |  2 +-
 5 files changed, 14 insertions(+), 15 deletions(-)
```

**Review by floridoo — APPROVED** [review]

**Comment by floridoo** [comment]
This should fix the tests: https://github.com/mesosphere/charts/pull/1389

**Review by cbuto — APPROVED** [review]

**Comment by cbuto** [comment]
I looked at this a bit and it seems like we have to `helm repo add` the cost-analyzer helm repo. I'm not sure if there's a way we can dynamically add all the helm repos we need when running `ct lint`.

I did try explicitly defining the repo and that worked - https://github.com/mesosphere/charts/pull/1391/files

**Comment by gracedo** [comment]
Thanks for looking into it @cbuto ! I cherry-picked your commit and also added an additional commit to add all the helm repos (copied from https://github.com/mesosphere/charts/blob/master/test/helm3/ct-e2e.yaml#L37-L46 for reference)

**Pull request merged**
