### PR TITLE
[dispatch] Update version

### PR DESCRIPTION
**Pull request by cprovencher**

### CODE REVIEW

**Comment by alejandroEsc** [comment]
Are we sure we are trying chart version to app version?

**Comment by GoelDeepak** [comment]
Did we do the upgrade testing and verify it passes?

**Comment by dkoshkin** [comment]
This is outdated as there is 0.5.2 already. Is this needed if the chart is being used in kubernetes-base-addons is coming from the dispatch repo?

**Comment by jbarrick-mesosphere** [comment]
This is not needed as we maintain our chart here: https://github.com/mesosphere/dispatch/tree/master/charts/dispatch

This chart is only still here in case there are still people using Konvoy 1.2.

**Pull request closed without merging**
