### PR TITLE
[velero] fix: allow velero to deploy on helm2&3 without needing install hooks

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What type of PR is this?**

BUG

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-70289

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by samvantran** [comment]
Should we run an AWS e2e test against Konvoy master so that we know this will work on Konvoy? Want to make sure we don't get caught again. (if the test fails with ubi8, someone is already looking into that one).

**Comment by alejandroEsc** [comment]
> Should we run an AWS e2e test against Konvoy master so that we know this will work on Konvoy? Want to make sure we don't get caught again. (if the test fails with ubi8, someone is already looking into that one).

Suggestions about which test and where? Do you mean a manual test?

**Comment by dlipovetsky** [comment]
Thanks for fixing this @alejandroEsc!

Could you please amend the README (or document in a separate file) how CRD management works? There are CRDs in the `crds/` folder, there are CRDs in `files/crds.yaml`, and of course, there's the `templates/install-crds.yaml` What gets used when, I still don't have straight, unfortunately, and I would appreciate having a reference.

**Comment by alejandroEsc** [comment]
> Thanks for fixing this @alejandroEsc!
> 
> Could you please amend the README (or document in a separate file) how CRD management works? There are CRDs in the `crds/` folder, there are CRDs in `files/crds.yaml`, and of course, there's the `templates/install-crds.yaml` What gets used when, I still don't have straight, unfortunately, and I would appreciate having a reference.

Sounds like a good idea. I will do so in another PR.

**Comment by alejandroEsc** [comment]
@samvantran the aws test passed https://github.com/mesosphere/kubernetes-base-addons/pull/423, however since this is a chart that needs pv, i suspect this is why the ci test is failing

**Comment by samvantran** [comment]
> however since this is a chart that needs pv, i suspect this is why the ci test is failing

another area to improve in testing. can we fix that in the testing framework?

**Pull request merged**
