### PR TITLE
chore: bump KCL to v0.2.5

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by hectorj2f** [comment]
@jimmidyson this is awkward:
```
[22:15:17][Step 1/1] >>> git show origin/dev:stable/kommander/Chart.yaml
[22:15:17][Step 1/1] Old chart version: 0.2.24
[22:15:17][Step 1/1] New chart version: 0.2.24
```

**Comment by hectorj2f** [comment]
I can see in our index https://mesosphere.github.io/charts/stable/index.yaml a version 0.2.24 🤔

**Comment by hectorj2f** [comment]
https://github.com/mesosphere/charts/commit/b4c9cfbe6a6dcc2bd57880199d882463abaf845e

**Comment by jimmidyson** [comment]
Just hadn't rebased...

**Comment by hectorj2f** [comment]
I already rebased it for you, LOL.

**Pull request merged**
