### PR TITLE
update kommander catalog api to latest

### PR DESCRIPTION
**Pull request by shaneutt**
As per [D2IQ-64402](https://jira.d2iq.com/browse/D2IQ-64402) this PR updates the helm chart for the kommander catalog api to the latest release version `v0.8.3`.

### CODE REVIEW

**Comment by shaneutt** [comment]
@mesosphere/sig-ksphere-catalog it's late night for me, if anyone has some spare cycles to check on the CI issues here for me it would be appreciated :vulcan_salute:

**Comment by joejulian** [comment]
Looking at CI

**Comment by jaxesn** [comment]
Just a reminder this is also defined in the add-on

https://github.com/mesosphere/kubeaddons-kommander/blob/master/addons/kommander/1.x/kommander.yaml#L75

**Comment by shaneutt** [comment]
> Just a reminder this is also defined in the add-on
> 
> https://github.com/mesosphere/kubeaddons-kommander/blob/master/addons/kommander/1.x/kommander.yaml#L75

Yes indeed, I was on top of this, in the JIRA [D2IQ-64402](https://jira.d2iq.com/browse/D2IQ-64402) I have a follow up item to update Kommander once this updates, chart and addon :+1:

**Comment by juliangieseke** [comment]
included and merged in #471

**Pull request closed without merging**
