### PR TITLE
Feat: Add new vsphere-csi-driver chart

### PR DESCRIPTION
**Pull request by sebbrandt87**
**What type of PR is this?**

Feature

**What this PR does/ why we need it**:

- adapted from upstream manifests

**Which issue(s) this PR fixes**:

[D2IQ-71493]

[D2IQ-71493]: https://jira.d2iq.com/browse/D2IQ-71493

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
vsphere-csi-driver added
```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by sebbrandt87** [comment]
There are no changes for this chart that should let the tests fail.
Lint is ✅

**Review by shaneutt — APPROVED** [review]
LGTM, what's our testing story for this driver so far?

**Comment by joejulian** [comment]
Us this an unaltered fork if upstream? Can we just use the upstream chart directly?

**Comment by sebbrandt87** [comment]
> LGTM, what's our testing story for this driver so far?

It will follow after alpha implementation.

**Comment by sebbrandt87** [comment]
> Is this an unaltered fork of upstream? Can we just use the upstream chart directly?

It is not an unaltered fork of upstream https://github.com/helm/charts/tree/master/stable/vsphere-cpi, this is a direct chart creation out of official kubernetes-sigs repository https://github.com/kubernetes-sigs/vsphere-csi-driver/tree/master/manifests/v2.0.0

I wouldn't say the `helm/charts` is the official one for that CSI driver. We see that a lot of charts are moving to own chart repos. 

Also I see you point that we may should contribute to the helm/chart repo to match with the latest manifests changes from kubernetes-sigs repository.

I can check again compability of helm/chart and kubernetes-sigs manifests.

**Comment by joejulian** [comment]
I agree. helm/charts is deprecated.

Thanks for pointing me to the manifest. I get why we're maintaining our own chart now.

LGTM

**Review by joejulian — APPROVED** [review]

**Pull request merged**
