### PR TITLE
kubecost: Upgrade kubecost dep to 1.64.0

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

Upgrade kubecost dep to 1.64.0 to stay up to date

**Which issue(s) this PR fixes**:

no issue

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by alejandroEsc — APPROVED** [review]

**Review by samvantran — APPROVED** [review]

**Comment by samvantran** [comment]
Anything worth mentioning as far as new features/fixes?

**Comment by alejandroEsc** [comment]
Helm2 testing is broken atm since cert-manager is using a crd that is apiextensions/v1 and not v1beta1 which helm2 currently only supports. This will not change since this helm2 bug fixes are not accepted any longer. If we are in a rush to merge this PR in, I am all in since I saw this be green before the cert-manager change.

**Comment by gracedo** [comment]
There's no rush, this is just stay up to date, no significant features or fixes that we need. Here's the kubecost release notes for set of changes https://github.com/kubecost/cost-analyzer-helm-chart/releases

**Review by branden — APPROVED** [review]

**Pull request merged**
