### PR TITLE
fix: add clippy js for clipboard support

### PR DESCRIPTION
**Pull request by jr0d**
These javasciprt libraries must be loaded for clipboard widgets to function.

### CODE REVIEW

**Comment by jr0d** [comment]
@mesosphere/sig-ksphere-catalog How do I get these tests to run?

**Comment by makkes** [comment]
> @mesosphere/sig-ksphere-catalog How do I get these tests to run?

I already asked DevProd but haven't gotten a response, yet: https://mesosphere.slack.com/archives/C5U03P5T6/p1592310634025100

**Pull request merged**
